import { UserNavbar } from "@/app/dashboard/_components/navBar";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
